# Generated by Django 5.2.3 on 2025-06-26 12:15

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Title of the chat conversation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "ui_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="UI messages for the chat conversation, sent by frontend, not used",
                    ),
                ),
                (
                    "openai_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="OpenAI messages for the chat conversation, not used",
                    ),
                ),
                (
                    "messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Stored messages for the chat conversation, sent to frontend",
                    ),
                ),
                (
                    "agent_usage",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Agent usage for the chat conversation, provided by OpenAI API",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
