# Generated by Django 5.2.3 on 2025-07-28 09:59

import django.core.serializers.json
from django.db import migrations

import django_pydantic_field.compat.django
import django_pydantic_field.fields

import chat.ai_sdk_types


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversation",
            name="messages",
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Stored messages for the chat conversation, sent to frontend",
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (chat.ai_sdk_types.UIMessage,)
                ),
            ),
        ),
    ]
