# Generated by Django 5.2.3 on 2025-09-17 12:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_fix_source_type_in_messages"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversationContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("document", "Document")],
                        help_text="Kind of the chat conversation context (e.g., 'image', 'document')",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Key of the chat conversation context", max_length=100
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Value of the chat conversation context", null=True
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contexts",
                        to="chat.chatconversation",
                    ),
                ),
            ],
            options={
                "unique_together": {("conversation", "name")},
            },
        ),
    ]
