# Generated by Django 5.2.7 on 2025-10-17 16:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.file_upload.enums


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatconversationcontext"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "upload_state",
                    models.CharField(
                        choices=core.file_upload.enums.AttachmentStatus.choices,
                        default=core.file_upload.enums.AttachmentStatus["PENDING"],
                        max_length=40,
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="File path of the attachment in the object storage"),
                ),
                ("file_name", models.CharField(help_text="Original name of the attachment file")),
                (
                    "content_type",
                    models.CharField(help_text="MIME type of the attachment file", max_length=100),
                ),
                ("size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the attachment",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversion_from",
                    models.CharField(
                        blank=True,
                        help_text="Original file key if the Markdown from another file",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="ChatConversationContext",
        ),
    ]
