# Generated by Django 5.2.3 on 2025-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_chatconversation_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="collection_id",
            field=models.CharField(
                blank=True,
                help_text="Collection ID for the conversation, used for RAG document search",
                null=True,
            ),
        ),
    ]
