# Generated by Django 5.2.9 on 2026-01-07 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatconversationattachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(help_text='Git commit SHA from which this prompt was synced.', max_length=40)),
                ('content', models.TextField(help_text='Jinja template content of the prompt.')),
                ('metadata', models.JSONField(blank=True, help_text='Optional JSON metadata loaded from the sidecar .meta.json file.', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
