# Generated by Django 5.2.9 on 2025-12-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_chatconversationattachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="title_set_by_user_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user manually set the title. If set, prevent automatic title generation.",
                null=True,
            ),
        ),
    ]
