# Generated by Django 5.2.11 on 2026-02-25 16:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatconversation_title_set_by_user_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("title", models.CharField(help_text="Title of the chat project", max_length=100)),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("folder", "Folder icon"),
                            ("file", "File icon"),
                            ("perso", "Perso icon"),
                            ("gear", "Gear icon"),
                            ("megaphone", "Megaphone icon"),
                            ("star", "Star icon"),
                            ("bookmark", "Bookmark icon"),
                            ("chart", "Chart icon"),
                            ("euro", "Euro icon"),
                            ("key", "Key icon"),
                            ("justice", "Justice icon"),
                            ("book", "Book icon"),
                            ("puzzle", "Puzzle icon"),
                            ("palette", "Palette icon"),
                            ("terminal", "Terminal icon"),
                            ("car", "Car icon"),
                            ("music", "Music icon"),
                            ("checkmark", "Checkmark icon"),
                            ("la_suite", "La Suite icon"),
                        ],
                        help_text="Project icon",
                        max_length=20,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("color_1", "Color 1"),
                            ("color_2", "Color 2"),
                            ("color_3", "Color 3"),
                            ("color_4", "Color 4"),
                            ("color_5", "Color 5"),
                            ("color_6", "Color 6"),
                            ("color_7", "Color 7"),
                            ("color_8", "Color 8"),
                            ("color_9", "Color 9"),
                        ],
                        help_text="Project icon color",
                        max_length=20,
                    ),
                ),
                (
                    "llm_instructions",
                    models.TextField(
                        blank=True, help_text="Custom user instructions to be sent to the llm"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="chat.chatproject",
            ),
        ),
    ]
