# Generated by Django 5.2.12 on 2026-04-09 11:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatproject_chatconversation_project"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("albert", "Albert"), ("find", "Find")],
                        help_text="RAG backend key",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Backend-specific collection ID (Albert int, Find UUID, etc.)",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name, e.g. 'conversation-{pk}' or 'project-{pk}'",
                        max_length=255,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to="chat.chatproject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_entries",
                        to="chat.chatconversationattachment",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="chat.collection",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("conversation__isnull", False), ("project__isnull", True)),
                    models.Q(("conversation__isnull", True), ("project__isnull", False)),
                    _connector="OR",
                ),
                name="collection_owner_exactly_one",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("conversation__isnull", False)),
                fields=("conversation", "backend"),
                name="one_collection_per_backend_per_conversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("project", "backend"),
                name="one_collection_per_backend_per_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectiondocument",
            constraint=models.UniqueConstraint(
                fields=("collection", "attachment"),
                name="one_document_per_collection_per_attachment",
            ),
        ),
    ]
