# Generated by Django 5.2.11 on 2026-02-25 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatproject_chatconversation_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["owner", "-created_at"], name="chat_chatco_owner_i_48266a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(fields=["owner", "project"], name="chat_chatco_owner_i_38d719_idx"),
        ),
    ]
