# Generated by Django 5.2.13 on 2026-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatproject_chatconversation_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversationattachment",
            name="transcription_job_id",
            field=models.CharField(
                blank=True,
                help_text="Job ID returned by meet/summary transcription service",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
