# Generated by Django 5.2.13 on 2026-05-05 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_chatproject_chatconversation_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversationattachment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatproject",
            ),
        ),
        migrations.AddField(
            model_name="chatconversationattachment",
            name="rag_document_id",
            field=models.CharField(
                blank=True,
                help_text="Per-document id returned by the RAG backend at indexing time, used to remove the document from its collection on attachment delete",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatproject",
            name="collection_id",
            field=models.CharField(
                blank=True,
                help_text="Collection ID for the project, used for RAG document search across project files",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatconversationattachment",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="chat.chatconversation",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatconversationattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("conversation__isnull", False), ("project__isnull", True)),
                    models.Q(("conversation__isnull", True), ("project__isnull", False)),
                    _connector="OR",
                ),
                name="attachment_owner_exactly_one",
            ),
        ),
    ]
