# Generated by Django 5.2.13 on 2026-05-27 14:42

from django.db import migrations, models

import chat.enums


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chatconversationattachment_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="index_state",
            field=models.CharField(
                choices=[
                    ("unindexed", "UNINDEXED"),
                    ("deindexed", "DEINDEXED"),
                    ("indexing", "INDEXING"),
                    ("indexed", "INDEXED"),
                    ("error", "ERROR"),
                ],
                default=chat.enums.CollectionIndexState["UNINDEXED"],
                help_text="Current indexing state of this conversation's RAG collection",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatconversationattachment",
            name="is_indexed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this attachment has been indexed in the RAG backend",
            ),
        ),
    ]
