# Generated by Django 5.2.13 on 2026-05-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_chatconversationattachment_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelHealth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "model_id", "-updated_at"],
                        name="chat_modelh_provide_57f059_idx",
                    )
                ],
            },
        ),
    ]
