# Generated by Django 5.2.13 on 2026-05-27 14:42

from django.db import migrations, models


def backfill_conversation_index_state(apps, schema_editor):
    apps.get_model("chat", "ChatConversation").objects.filter(collection_id__isnull=False).exclude(
        collection_id=""
    ).update(index_state="indexed")


def backfill_attachment_is_indexed(apps, schema_editor):
    apps.get_model("chat", "ChatConversationAttachment").objects.filter(
        rag_document_id__isnull=False
    ).exclude(rag_document_id="").update(is_indexed=True)


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_modelhealth"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="index_state",
            field=models.CharField(
                choices=[
                    ("unindexed", "UNINDEXED"),
                    ("deindexed", "DEINDEXED"),
                    ("indexing", "INDEXING"),
                    ("indexed", "INDEXED"),
                    ("error", "ERROR"),
                ],
                default="unindexed",
                help_text="Current indexing state of this conversation's RAG collection",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatconversationattachment",
            name="is_indexed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this attachment has been indexed in the RAG backend",
            ),
        ),
        migrations.RunPython(
            code=backfill_conversation_index_state,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=backfill_attachment_is_indexed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
