# Generated by Django 5.2.12 on 2026-04-12 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_migrate_collection_id_to_collection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversationattachment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatproject'),
        ),
        migrations.AlterField(
            model_name='chatconversationattachment',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatconversation'),
        ),
        migrations.AddConstraint(
            model_name='chatconversationattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('conversation__isnull', False), ('project__isnull', True)), models.Q(('conversation__isnull', True), ('project__isnull', False)), _connector='OR'), name='attachment_owner_exactly_one'),
        ),
    ]
