# Generated by Django 5.2.14 on 2026-06-10 16:36

from django.db import migrations, models


def orange_to_yellow(apps, schema_editor):
    """Rewrite legacy 'orange' health records to the renamed 'yellow' status."""
    ModelHealth = apps.get_model("chat", "ModelHealth")
    ModelHealth.objects.filter(status="orange").update(status="yellow")


def yellow_to_orange(apps, schema_editor):
    """Reverse: restore 'yellow' health records to the former 'orange' status."""
    ModelHealth = apps.get_model("chat", "ModelHealth")
    ModelHealth.objects.filter(status="yellow").update(status="orange")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0009_chatconversation_index_state_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelhealth",
            name="status",
            field=models.CharField(
                choices=[("green", "Green"), ("yellow", "Yellow"), ("red", "Red")], max_length=10
            ),
        ),
        migrations.RunPython(orange_to_yellow, yellow_to_orange),
    ]
