# Generated by Django 5.2.14 on 2026-06-25 11:11

from django.conf import settings
from django.db import migrations, models


def set_default_model_hrid(apps, schema_editor):
    """Pin existing conversations to the default LLM HRID."""
    ChatConversation = apps.get_model("chat", "ChatConversation")
    ChatConversation.objects.update(model_hrid=settings.LLM_DEFAULT_MODEL_HRID)


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0010_alter_modelhealth_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="model_hrid",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HRID of the LLM pinned to this conversation. Set on the first message and kept for the whole conversation so a recovered main model does not move ongoing chats. Empty string means 'not yet pinned'.",
                max_length=100,
            ),
        ),
        migrations.RunPython(
            set_default_model_hrid,
            migrations.RunPython.noop,
        ),
    ]
