# Generated by Django 5.2.14 on 2026-06-25 14:07

from django.db import migrations, models

import chat.enums


def backfill_attachment_index_state(apps, schema_editor):
    """Classify rows already indexed before `index_state` existed.

    The synchronous project indexing flow that predates this field records a
    backend `rag_document_id` (Albert) or flips the legacy `is_indexed` flag
    (Find returns no per-document id). Mark those rows INDEXED so the API/UI
    does not report already-indexed attachments as not indexed; rows with
    neither signal keep the NOT_INDEXED default.
    """
    attachment_model = apps.get_model("chat", "ChatConversationAttachment")
    attachment_model.objects.filter(
        models.Q(is_indexed=True)
        | (models.Q(rag_document_id__isnull=False) & ~models.Q(rag_document_id=""))
    ).update(index_state="indexed")


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_chatconversation_model_hrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversationattachment",
            name="index_state",
            field=models.CharField(
                choices=[
                    ("not_indexed", "NOT_INDEXED"),
                    ("indexing", "INDEXING"),
                    ("indexed", "INDEXED"),
                    ("failed", "FAILED"),
                ],
                default=chat.enums.AttachmentIndexState["NOT_INDEXED"],
                help_text="Per-attachment RAG indexing lifecycle (set by the project indexing task)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatconversationattachment",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Human-readable reason the last indexing attempt failed, if any",
                null=True,
            ),
        ),
        migrations.RunPython(
            code=backfill_attachment_index_state,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
