# Generated by Django 5.2.14 on 2026-06-25 14:07

from django.db import migrations, models

import chat.enums


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0011_chatconversation_model_hrid"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversationattachment",
            name="index_state",
            field=models.CharField(
                choices=[
                    ("not_indexed", "NOT_INDEXED"),
                    ("indexing", "INDEXING"),
                    ("indexed", "INDEXED"),
                    ("failed", "FAILED"),
                ],
                default=chat.enums.AttachmentIndexState["NOT_INDEXED"],
                help_text="Per-attachment RAG indexing lifecycle (set by the project indexing task)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatconversationattachment",
            name="processing_error",
            field=models.TextField(
                blank=True,
                help_text="Human-readable reason the last indexing attempt failed, if any",
                null=True,
            ),
        ),
    ]
