# Generated by Django 5.2.14 on 2026-06-30 21:45

import chat.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_chatconversationattachment_index_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversationattachment',
            name='index_state',
            field=models.CharField(choices=[('not_indexed', 'NOT_INDEXED'), ('indexing', 'INDEXING'), ('indexed', 'INDEXED'), ('failed', 'FAILED')], default=chat.enums.AttachmentIndexState['NOT_INDEXED'], help_text='Per-attachment RAG indexing lifecycle (set by the project and conversation indexing tasks)', max_length=20),
        ),
    ]
