# Generated by Django 5.2.14 on 2026-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0012_chatconversationattachment_index_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatconversation",
            name="history_summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Latest generated conversation summary used as system context",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="history_summary_checkpoint",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of pydantic history messages already compacted into history_summary",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="history_summary_claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "When a worker claimed summary generation; claims expire after "
                    "HISTORY_SUMMARY_CLAIM_TTL_SECONDS (dead-worker liveness bound)"
                ),
                null=True,
            ),
        ),
    ]
