# Generated by Django 5.2.15 on 2026-07-28 10:05

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    # CONCURRENTLY cannot run inside a transaction, and the conversation table is
    # large enough in production that a plain CREATE INDEX would block writes.
    atomic = False

    dependencies = [
        ("chat", "0013_chatconversation_history_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="chatconversation",
            index=models.Index(
                fields=["-updated_at", "-id"], name="chat_chatco_updated_e2bf86_idx"
            ),
        ),
    ]
