# Generated by Django 5.2.17 on 2026-10-01 13:46

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import chat.enums
import chat.models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_chatconversation_chat_chatco_updated_e2bf86_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArenaExperiment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Only one experiment can be active at a time."
                    ),
                ),
                (
                    "champion_model_hrid",
                    models.CharField(
                        default=chat.models.default_champion_hrid,
                        help_text="HRID of the production model every challenger is compared against.",
                        max_length=100,
                    ),
                ),
                (
                    "sampling_rate",
                    models.FloatField(
                        default=0.1,
                        help_text="Share of eligible turns that become arena turns (0 to 1).",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "daily_cap_per_user",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum arena turns a single user sees per day."
                    ),
                ),
                (
                    "min_votes_for_conclusion",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Below this number of votes a challenger row is labeled 'indicative' on the results page. A label, not a gate.",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_arena_results", "Can view arena results")],
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="arena_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ArenaComparison",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "turn",
                    models.PositiveIntegerField(
                        default=0, help_text="Index of the user message in the conversation."
                    ),
                ),
                (
                    "tools_stripped",
                    models.BooleanField(
                        default=False, help_text="Side-effect tools were removed from both models."
                    ),
                ),
                ("champion_model_hrid", models.CharField(max_length=100)),
                ("challenger_model_hrid", models.CharField(max_length=100)),
                (
                    "champion_side",
                    models.CharField(choices=[("left", "LEFT"), ("right", "RIGHT")], max_length=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("voted", "VOTED"),
                            ("abandoned", "ABANDONED"),
                            ("errored", "ERRORED"),
                        ],
                        default=chat.enums.ArenaComparisonStatus["PENDING"],
                        max_length=10,
                    ),
                ),
                (
                    "winner",
                    models.CharField(
                        blank=True,
                        choices=[("champion", "CHAMPION"), ("challenger", "CHALLENGER")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("drawn_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("voted_at", models.DateTimeField(blank=True, null=True)),
                ("time_to_vote_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("conversation_version", models.PositiveIntegerField(default=0)),
                ("input_snapshot", models.JSONField(blank=True, null=True)),
                ("closed_reason", models.CharField(blank=True, default="", max_length=30)),
                ("champion_started_at", models.DateTimeField(blank=True, null=True)),
                ("challenger_started_at", models.DateTimeField(blank=True, null=True)),
                ("champion_prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("champion_completion_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("champion_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("champion_first_token_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("champion_co2_impact", models.FloatField(blank=True, null=True)),
                ("champion_trace_id", models.CharField(blank=True, default="", max_length=100)),
                ("champion_finished_at", models.DateTimeField(blank=True, null=True)),
                ("champion_error", models.TextField(blank=True, default="")),
                ("champion_payload", models.JSONField(blank=True, null=True)),
                (
                    "champion_committed",
                    models.BooleanField(
                        default=False,
                        help_text="The champion answer is already in the conversation history. It is written as soon as the champion finishes so nothing is lost if the user never votes; a vote for the challenger swaps it.",
                    ),
                ),
                ("challenger_prompt_tokens", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "challenger_completion_tokens",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("challenger_latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("challenger_first_token_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("challenger_co2_impact", models.FloatField(blank=True, null=True)),
                ("challenger_trace_id", models.CharField(blank=True, default="", max_length=100)),
                ("challenger_finished_at", models.DateTimeField(blank=True, null=True)),
                ("challenger_error", models.TextField(blank=True, default="")),
                ("challenger_payload", models.JSONField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_comparisons",
                        to="chat.chatconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arena_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comparisons",
                        to="chat.arenaexperiment",
                    ),
                ),
            ],
            options={
                "ordering": ["-drawn_at"],
                "indexes": [
                    models.Index(
                        fields=["experiment", "status"], name="chat_arenac_experim_fc5968_idx"
                    ),
                    models.Index(
                        fields=["user", "drawn_at"], name="chat_arenac_user_id_ea5ec8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ArenaChallenger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                ("model_hrid", models.CharField(max_length=100)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challengers",
                        to="chat.arenaexperiment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("experiment", "model_hrid"),
                        name="arena_challenger_unique_per_experiment",
                    )
                ],
            },
        ),
    ]
