# Generated by Django 5.2.17 on 2026-10-01 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_chatconversation_chat_chatco_updated_e2bf86_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingTierSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "simple_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 1 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "simple_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 1 alternatives."
                    ),
                ),
                (
                    "standard_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 2 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "standard_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 2 alternatives."
                    ),
                ),
                (
                    "complex_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier 3 model. Blank means 'use the LLM_TIER_*_MODEL_HRID setting', which itself defaults to LLM_DEFAULT_MODEL_HRID.",
                        max_length=100,
                    ),
                ),
                (
                    "complex_alternatives",
                    models.JSONField(
                        blank=True, default=list, help_text="HRIDs of the tier 3 alternatives."
                    ),
                ),
                (
                    "router_model_hrid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Classifier model. Blank means 'use the LLM_ROUTER_MODEL_HRID setting'.",
                        max_length=100,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Tiers 1 and 3 are chosen only at or above this classifier confidence.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Routing Tier Settings",
            },
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="last_routing",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Routing decision of the last turn (tier, model_hrid and classifier labels), used as a hint by the router on the next turn.",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="pinned_tier",
            field=models.CharField(
                blank=True,
                choices=[("simple", "SIMPLE"), ("standard", "STANDARD"), ("complex", "COMPLEX")],
                help_text="Complexity tier the user pinned on this conversation. Null means Auto: the router picks the tier on every turn.",
                max_length=20,
                null=True,
            ),
        ),
    ]
