# Generated by Django 5.2.17 on 2026-09-23 15:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0014_chatconversation_chat_chatco_updated_e2bf86_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatStreamChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "run_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="The turn that wrote this chunk. Everything is scoped to it rather than to the conversation, so two turns running at once - two tabs on the same conversation - cannot fold, overwrite or delete each other's trail.",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Id of the assistant message being streamed, as announced to the client in the `start` frame, so the folded message is the one the client is already holding. Blank on the chunk holding the question, which is written before there is an answer for the id to belong to.",
                        max_length=255,
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        help_text="Position of this chunk in the turn, starting at 0"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", help_text="Text produced since the previous chunk"
                    ),
                ),
                (
                    "parts",
                    models.JSONField(
                        blank=True,
                        help_text="Snapshot of the turn's messages at this point, written instead of `text` when the turn's structure changes (a tool call, a tool result). Null on a text chunk.",
                        null=True,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation whose current turn produced this chunk",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stream_chunks",
                        to="chat.chatconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "chat stream chunk",
                "verbose_name_plural": "chat stream chunks",
                "db_table": "chat_stream_chunk",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "run_id", "seq"],
                        name="chat_stream_convers_1c9384_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("conversation", "run_id", "seq"), name="unique_stream_chunk_seq"
                    )
                ],
            },
        ),
    ]
