# Generated by Django 5.2.7 on 2025-10-09 08:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import activation_codes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=activation_codes.models.generate_activation_code,
                        help_text="The activation code that users will enter",
                        max_length=50,
                        unique=True,
                        verbose_name="activation code",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times this code can be used. 0 means unlimited.",
                        verbose_name="maximum uses",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Number of times this code has been used",
                        verbose_name="current uses",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this code can still be used",
                        verbose_name="active",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when this code expires",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Internal description or notes about this code",
                        verbose_name="description",
                    ),
                ),
            ],
            options={
                "verbose_name": "activation code",
                "verbose_name_plural": "activation codes",
                "db_table": "activation_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "activation_code",
                    models.ForeignKey(
                        help_text="The activation code that was used",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="activation_codes.activationcode",
                        verbose_name="activation code",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who used the activation code",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "user activation",
                "verbose_name_plural": "user activations",
                "db_table": "user_activation",
                "ordering": ["-created_at"],
            },
        ),
    ]
