# Generated by Django 5.2.3 on 2025-09-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_conversation_analytics",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user allows to use their conversations for analytics.",
                verbose_name="allow conversation analytics",
            ),
        ),
    ]
