# Generated by Django 5.2.8 on 2025-12-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_allow_conversation_analytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="short name"),
        ),
    ]
