# Generated by Django 5.2.9 on 2026-01-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_banner_title', models.CharField(blank=True, verbose_name='Environment banner - title')),
                ('environment_banner_content', models.TextField(blank=True, verbose_name='Environment banner - content')),
                ('environment_banner_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=20, verbose_name='Environment banner - level')),
                ('status_banner_title', models.CharField(blank=True, verbose_name='Status banner - title')),
                ('status_banner_content', models.TextField(blank=True, verbose_name='Status banner - content')),
                ('status_banner_level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=20, verbose_name='Status banner - level')),
                ('status_banner_dismissible', models.BooleanField(default=True, help_text='Allow users to dismiss this banner', verbose_name='Status banner - dismissible')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
