# Generated by Django 5.2.9 on 2025-12-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_smart_web_search",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user allows to use smart web search features.",
                verbose_name="allow smart web search",
            ),
        ),
    ]
