# Generated by Django 5.2.13 on 2026-04-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_allow_smart_web_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "self_documentation",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Self documentation content. Must be valid markdown.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
