# Generated by Django 5.2.13 on 2026-05-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_user_allow_smart_web_search_default_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="status_banner_content",
            field=models.TextField(blank=True, verbose_name="Status banner - content"),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="status_banner_ends_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, the banner is hidden after this date.",
                null=True,
                verbose_name="Status banner - ends at",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="status_banner_level",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("alert", "Alert")],
                default="info",
                max_length=20,
                verbose_name="Status banner - level",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="status_banner_starts_at",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, the banner is hidden before this date.",
                null=True,
                verbose_name="Status banner - starts at",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="status_banner_title",
            field=models.CharField(blank=True, verbose_name="Status banner - title"),
        ),
    ]
