# Generated by Django 5.2.14 on 2026-06-08 12:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_maintenancemode_updated_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessBypassEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="primary key for the record as UUID",
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="date and time at which a record was created",
                        verbose_name="created on",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="date and time at which a record was last updated",
                        verbose_name="updated on",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="email address allowed to bypass the role requirement",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="inactive entries are ignored without being deleted",
                        verbose_name="active",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="optional reason for granting this bypass",
                        verbose_name="note",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="optional date after which this bypass no longer applies",
                        null=True,
                        verbose_name="expires on",
                    ),
                ),
            ],
            options={
                "verbose_name": "access bypass email",
                "verbose_name_plural": "access bypass emails",
                "db_table": "conversations_access_bypass_email",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="user",
            name="organization_siret",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SIRET of the user's organization, as provided by the identity provider.",
                max_length=14,
                verbose_name="organization SIRET",
            ),
        ),
    ]
