# Generated by Django 5.2.14 on 2026-06-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_accessbypassemail_user_organization_siret"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatCooldownSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "window_seconds",
                    models.PositiveIntegerField(
                        default=1200,
                        help_text="Length of the trailing token-usage window, in seconds.",
                    ),
                ),
                (
                    "token_threshold",
                    models.PositiveIntegerField(
                        default=650000,
                        help_text="Tokens over the window above which a cooldown can apply.",
                    ),
                ),
                (
                    "default_factor",
                    models.FloatField(
                        default=0.0016,
                        help_text="Seconds of cooldown per token over the threshold, when a model defines no cooldown_factor of its own.",
                    ),
                ),
                (
                    "min_seconds",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minimum cooldown once the threshold is crossed, in seconds.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Cooldown Settings",
            },
        ),
    ]
