# Generated by Django 5.2.14 on 2026-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_chatcooldownsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="block_on_full_outage",
            field=models.BooleanField(
                default=True,
                help_text="When enabled, the chat input is disabled while all AI models are unavailable. Disable to keep the input active and show a degraded-service warning instead.",
                verbose_name="Block chat input on full outage",
            ),
        ),
    ]
