# Generated by Django 5.2.14 on 2026-06-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_siteconfiguration_block_on_full_outage"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelhealthsettings",
            name="fallback_eviction_threshold",
            field=models.CharField(
                choices=[("yellow", "Yellow"), ("red", "Red")],
                default="red",
                help_text="Minimum fallback-model health to skip to the next fallback. Applied uniformly to fallback 1 and fallback 2. 'yellow' = skip yellow fallbacks (aggressive). 'red' = accept yellow fallbacks, only skip on red.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="modelhealthsettings",
            name="main_eviction_threshold",
            field=models.CharField(
                choices=[("yellow", "Yellow"), ("red", "Red")],
                default="red",
                help_text="Minimum main-model health that triggers cascade to a fallback. 'yellow' = cascade on yellow or red (aggressive). 'red' = tolerate yellow on main, only cascade on red.",
                max_length=10,
            ),
        ),
    ]
