# Generated by Django 5.2.17 on 2026-09-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_modelhealthsettings_fallback_eviction_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_datagouv_connector",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user enabled the data.gouv connector.",
                verbose_name="allow data.gouv connector",
            ),
        ),
    ]
