"""
Django settings for conversations project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# pylint: disable=too-many-lines

import os
import tomllib
from socket import gethostbyname, gethostname
from urllib.parse import urlparse

from django.utils.functional import lazy

import posthog
import sentry_sdk
from configurations import Configuration, pristinemethod, values
from corsheaders.defaults import default_headers
from cryptography.fernet import Fernet
from langfuse import Langfuse
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import ignore_logger

from core.feature_flags.flags import FeatureFlags, FeatureToggle
from core.file_upload.enums import FileToLLMMode, FileUploadMode

from chat.llm_configuration import cached_load_llm_configuration, load_llm_configuration
from conversations.brave_settings import BraveSettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.getenv("DATA_DIR", os.path.join("/", "data"))


def get_release():
    """
    Get the current release of the application
    """
    try:
        with open(os.path.join(BASE_DIR, "pyproject.toml"), "rb") as f:
            pyproject_data = tomllib.load(f)
        return pyproject_data["project"]["version"]
    except FileNotFoundError, KeyError:
        return "NA"  # Default: not available


class Base(BraveSettings, Configuration):
    """
    This is the base configuration every configuration (aka environment) should inherit from. It
    is recommended to configure third-party applications by creating a configuration mixins in
    ./configurations and compose the Base configuration with those mixins.

    It depends on an environment variable that SHOULD be defined:

    * DJANGO_SECRET_KEY

    You may also want to override default configuration by setting the following environment
    variables:

    * SENTRY_DSN
    * DB_NAME
    * DB_HOST
    * DB_PASSWORD
    * DB_USER
    """

    DEBUG = False
    USE_SWAGGER = False

    API_VERSION = "v1.0"

    # Security
    ALLOWED_HOSTS = values.ListValue([])
    SECRET_KEY = values.Value(None)
    SERVER_TO_SERVER_API_TOKENS = values.ListValue([])

    # Application definition
    ROOT_URLCONF = "conversations.urls"
    WSGI_APPLICATION = "conversations.wsgi.application"

    # Database
    DATABASES = {
        "default": {
            "ENGINE": values.Value(
                "django.db.backends.postgresql_psycopg2",
                environ_name="DB_ENGINE",
                environ_prefix=None,
            ),
            "NAME": values.Value("conversations", environ_name="DB_NAME", environ_prefix=None),
            "USER": values.Value("dinum", environ_name="DB_USER", environ_prefix=None),
            "PASSWORD": values.Value("pass", environ_name="DB_PASSWORD", environ_prefix=None),
            "HOST": values.Value("localhost", environ_name="DB_HOST", environ_prefix=None),
            "PORT": values.Value(5432, environ_name="DB_PORT", environ_prefix=None),
        }
    }
    DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

    # Static files (CSS, JavaScript, Images)
    STATIC_URL = "/static/"
    STATIC_ROOT = os.path.join(DATA_DIR, "static")
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(DATA_DIR, "media")
    MEDIA_BASE_URL = values.Value(None, environ_name="MEDIA_BASE_URL", environ_prefix=None)

    SITE_ID = 1

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
        },
        "staticfiles": {
            "BACKEND": values.Value(
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
                environ_name="STORAGES_STATICFILES_BACKEND",
            ),
        },
    }

    # Media
    AWS_S3_ENDPOINT_URL = values.Value(environ_name="AWS_S3_ENDPOINT_URL", environ_prefix=None)
    AWS_S3_ACCESS_KEY_ID = values.Value(environ_name="AWS_S3_ACCESS_KEY_ID", environ_prefix=None)
    AWS_S3_SECRET_ACCESS_KEY = values.Value(
        environ_name="AWS_S3_SECRET_ACCESS_KEY", environ_prefix=None
    )
    AWS_S3_REGION_NAME = values.Value(environ_name="AWS_S3_REGION_NAME", environ_prefix=None)
    AWS_STORAGE_BUCKET_NAME = values.Value(
        "conversations-media-storage",
        environ_name="AWS_STORAGE_BUCKET_NAME",
        environ_prefix=None,
    )
    AWS_S3_SIGNATURE_VERSION = values.Value(
        "s3v4",
        environ_name="AWS_S3_SIGNATURE_VERSION",
        environ_prefix=None,
    )

    AWS_S3_UPLOAD_POLICY_EXPIRATION = values.Value(
        60,  # 1 minute
        environ_name="AWS_S3_UPLOAD_POLICY_EXPIRATION",
        environ_prefix=None,
    )
    AWS_S3_RETRIEVE_POLICY_EXPIRATION = values.Value(
        3 * 60,  # 3 minutes
        environ_name="AWS_S3_RETRIEVE_POLICY_EXPIRATION",
        environ_prefix=None,
    )
    AWS_S3_DOMAIN_REPLACE = values.Value(
        environ_name="AWS_S3_DOMAIN_REPLACE",
        environ_prefix=None,
    )

    ATTACHMENT_CHECK_UNSAFE_MIME_TYPES_ENABLED = values.BooleanValue(
        True,
        environ_name="ATTACHMENT_CHECK_UNSAFE_MIME_TYPES_ENABLED",
        environ_prefix=None,
    )
    ATTACHMENT_UNSAFE_MIME_TYPES = [
        # Executable Files
        "application/x-msdownload",
        "application/x-bat",
        "application/x-dosexec",
        "application/x-sh",
        "application/x-ms-dos-executable",
        "application/x-msi",
        "application/java-archive",
        "application/octet-stream",
        # Dynamic Web Pages
        "application/x-httpd-php",
        "application/x-asp",
        "application/x-aspx",
        "application/jsp",
        "application/xhtml+xml",
        "application/x-python-code",
        "application/x-perl",
        "text/html",
        "text/javascript",
        "text/x-php",
        # System Files
        "application/x-msdownload",
        "application/x-sys",
        "application/x-drv",
        "application/cpl",
        "application/x-apple-diskimage",
        # Script Files
        "application/javascript",
        "application/x-vbscript",
        "application/x-powershell",
        "application/x-shellscript",
        # Compressed/Archive Files
        "application/zip",
        "application/x-tar",
        "application/gzip",
        "application/x-bzip2",
        "application/x-7z-compressed",
        "application/x-rar",
        "application/x-rar-compressed",
        "application/x-compress",
        "application/x-lzma",
        # Macros in Documents
        "application/vnd.ms-word",
        "application/vnd.ms-excel",
        "application/vnd.ms-powerpoint",
        "application/vnd.ms-word.document.macroenabled.12",
        "application/vnd.ms-excel.sheet.macroenabled.12",
        "application/vnd.ms-powerpoint.presentation.macroenabled.12",
        # Disk Images & Virtual Disk Files
        "application/x-iso9660-image",
        "application/x-vmdk",
        "application/x-apple-diskimage",
        "application/x-dmg",
        # Other Dangerous MIME Types
        "application/x-ms-application",
        "application/x-msdownload",
        "application/x-shockwave-flash",
        "application/x-silverlight-app",
        "application/x-java-vm",
        "application/x-bittorrent",
        "application/hta",
        "application/x-csh",
        "application/x-ksh",
        "application/x-ms-regedit",
        "application/x-msdownload",
        "application/xml",
    ]
    ATTACHMENT_MAX_SIZE = values.IntegerValue(
        10 * (2**20),  # 10MB
        environ_name="ATTACHMENT_MAX_SIZE",
        environ_prefix=None,
    )
    FILE_UPLOAD_MODE = values.Value(
        FileUploadMode.PRESIGNED_URL,
        environ_name="FILE_UPLOAD_MODE",
        environ_prefix=None,
    )
    FILE_TO_LLM_MODE = values.Value(
        FileToLLMMode.PRESIGNED_URL,
        environ_name="FILE_TO_LLM_MODE",
        environ_prefix=None,
    )
    FILE_BACKEND_URL = values.Value(
        "",
        environ_name="FILE_BACKEND_URL",
        environ_prefix=None,
    )
    FILE_BACKEND_TEMPORARY_URL_EXPIRATION = values.IntegerValue(
        180,
        environ_name="FILE_BACKEND_TEMPORARY_URL_EXPIRATION",
        environ_prefix=None,
    )

    MALWARE_DETECTION = {
        "BACKEND": values.Value(
            "lasuite.malware_detection.backends.dummy.DummyBackend",
            environ_name="MALWARE_DETECTION_BACKEND",
            environ_prefix=None,
        ),
        "PARAMETERS": values.DictValue(
            default={
                "callback_path": "core.file_upload.malware_detection.malware_detection_callback",
            },
            environ_name="MALWARE_DETECTION_PARAMETERS",
            environ_prefix=None,
        ),
    }

    # Internationalization
    # https://docs.djangoproject.com/en/3.1/topics/i18n/

    # Languages
    LANGUAGE_CODE = values.Value("en-us")
    # cookie & language is set from frontend
    LANGUAGE_COOKIE_NAME = "conversation_language"
    LANGUAGE_COOKIE_PATH = "/"

    DRF_NESTED_MULTIPART_PARSER = {
        # output of parser is converted to querydict
        # if is set to False, dict python is returned
        "querydict": False,
    }

    # Careful! Languages should be ordered by priority, as this tuple is used to get
    # fallback/default languages throughout the app.
    LANGUAGES = values.SingleNestedTupleValue(
        (
            ("en-us", "English"),
            ("fr-fr", "Français"),
            # ("de-de", "Deutsch"),
            ("nl-nl", "Nederlands"),
            # ("es-es", "Español"),
        )
    )

    LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

    TIME_ZONE = "UTC"
    USE_I18N = True
    USE_TZ = True

    # Templates
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [os.path.join(BASE_DIR, "templates")],
            "OPTIONS": {
                "context_processors": [
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                    "django.template.context_processors.csrf",
                    "django.template.context_processors.debug",
                    "django.template.context_processors.i18n",
                    "django.template.context_processors.media",
                    "django.template.context_processors.request",
                    "django.template.context_processors.tz",
                ],
                "loaders": [
                    "django.template.loaders.filesystem.Loader",
                    "django.template.loaders.app_directories.Loader",
                ],
            },
        },
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",
        "core.middleware.MaintenanceMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.locale.LocaleMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "posthog.integrations.django.PosthogContextMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "dockerflow.django.middleware.DockerflowMiddleware",
    ]

    AUTHENTICATION_BACKENDS = [
        "django.contrib.auth.backends.ModelBackend",
        "core.authentication.backends.OIDCAuthenticationBackend",
    ]

    # Django applications from the highest priority to the lowest
    INSTALLED_APPS = [
        "activation_codes",
        "chat",
        "core",
        "demo",
        "drf_spectacular",
        # Third party apps
        "corsheaders",
        "django_filters",
        "dockerflow.django",
        "rest_framework",
        "solo.apps.SoloAppConfig",
        # Django
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.postgres",
        "django.contrib.sessions",
        "django.contrib.sites",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        # OIDC third party
        "mozilla_django_oidc",
        "lasuite.malware_detection",
    ]

    # Cache
    CACHES = {
        "default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"},
    }

    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "mozilla_django_oidc.contrib.drf.OIDCAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ),
        "DEFAULT_PARSER_CLASSES": [
            "rest_framework.parsers.JSONParser",
            "nested_multipart_parser.drf.DrfNestedParser",
        ],
        "DEFAULT_RENDERER_CLASSES": [
            # 🔒️ Disable BrowsableAPIRenderer which provides forms allowing a user to
            # see all the data in the database (ie a serializer with a ForeignKey field
            # will generate a form with a field with all possible values of the FK).
            "rest_framework.renderers.JSONRenderer",
        ],
        "EXCEPTION_HANDLER": "core.api.exception_handler",
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 20,
        "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_THROTTLE_RATES": {
            "attachment_upload": values.Value(
                default="60/minute",
                environ_name="API_ATTACHMENT_UPLOAD_THROTTLE_RATE",
                environ_prefix=None,
            ),
            "attachment_auth": values.Value(
                default="60/minute",
                environ_name="API_ATTACHMENT_AUTH_THROTTLE_RATE",
                environ_prefix=None,
            ),
            "file-stream": values.Value(
                default="60/minute",
                environ_name="API_FILE_STREAM_THROTTLE_RATE",
                environ_prefix=None,
            ),
        },
    }

    SPECTACULAR_SETTINGS = {
        "TITLE": "Conversations API",
        "DESCRIPTION": "This is the conversations API schema.",
        "VERSION": "1.0.0",
        "SERVE_INCLUDE_SCHEMA": False,
        "ENABLE_DJANGO_DEPLOY_CHECK": values.BooleanValue(
            default=False,
            environ_name="SPECTACULAR_SETTINGS_ENABLE_DJANGO_DEPLOY_CHECK",
        ),
        "COMPONENT_SPLIT_REQUEST": True,
        # OTHER SETTINGS
        "SWAGGER_UI_DIST": "SIDECAR",  # shorthand to use the sidecar instead
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
        "REDOC_DIST": "SIDECAR",
    }

    # Mail
    EMAIL_BACKEND = values.Value("django.core.mail.backends.smtp.EmailBackend")
    EMAIL_BRAND_NAME = values.Value(None)
    EMAIL_HOST = values.Value(None)
    EMAIL_HOST_USER = values.Value(None)
    EMAIL_HOST_PASSWORD = values.Value(None)
    EMAIL_LOGO_IMG = values.Value(None)
    EMAIL_PORT = values.PositiveIntegerValue(None)
    EMAIL_USE_TLS = values.BooleanValue(False)
    EMAIL_USE_SSL = values.BooleanValue(False)
    EMAIL_FROM = values.Value("from@example.com")

    AUTH_USER_MODEL = "core.User"

    # CORS
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_ALL_ORIGINS = values.BooleanValue(False)
    CORS_ALLOWED_ORIGINS = values.ListValue([])
    CORS_ALLOWED_ORIGIN_REGEXES = values.ListValue([])
    CORS_ALLOW_HEADERS = values.ListValue(
        [
            "x-posthog-distinct-id",
            "x-posthog-session-id",
        ],
        environ_name="CORS_ALLOW_HEADERS",
    ) + list(default_headers)

    # Sentry
    SENTRY_DSN = values.Value(None, environ_name="SENTRY_DSN", environ_prefix=None)

    # Frontend
    FRONTEND_THEME = values.Value(None, environ_name="FRONTEND_THEME", environ_prefix=None)
    FRONTEND_HOMEPAGE_FEATURE_ENABLED = values.BooleanValue(
        default=True,
        environ_name="FRONTEND_HOMEPAGE_FEATURE_ENABLED",
        environ_prefix=None,
    )
    FRONTEND_CSS_URL = values.Value(None, environ_name="FRONTEND_CSS_URL", environ_prefix=None)
    FRONTEND_DOCUMENTATION_URL = values.Value(
        None, environ_name="FRONTEND_DOCUMENTATION_URL", environ_prefix=None
    )
    FRONTEND_CONTACT_EMAIL = values.EmailValue(
        None, environ_name="FRONTEND_CONTACT_EMAIL", environ_prefix=None
    )
    FRONTEND_SILENT_LOGIN_ENABLED = values.BooleanValue(
        default=True, environ_name="FRONTEND_SILENT_LOGIN_ENABLED", environ_prefix=None
    )

    # Maintenance mode. When true, the app returns 503 to end-users for every
    # non-exempt request. Always OR'd with the DB-backed `MaintenanceMode` singleton.
    MAINTENANCE_MODE = values.BooleanValue(
        default=False, environ_name="MAINTENANCE_MODE", environ_prefix=None
    )

    # django-solo cache: avoids a DB hit per request for singleton lookups
    # (MaintenanceMode, SiteConfiguration). save() invalidates the cache key
    # instantly; the timeout is a safety net.
    SOLO_CACHE = "default"
    SOLO_CACHE_TIMEOUT = 60 * 5
    SOLO_CACHE_PREFIX = "solo"
    THEME_CUSTOMIZATION_FILE_PATH = values.Value(
        os.path.join(BASE_DIR, "conversations/configuration/theme/default.json"),
        environ_name="THEME_CUSTOMIZATION_FILE_PATH",
        environ_prefix=None,
    )

    THEME_CUSTOMIZATION_CACHE_TIMEOUT = values.Value(
        60 * 60 * 24,
        environ_name="THEME_CUSTOMIZATION_CACHE_TIMEOUT",
        environ_prefix=None,
    )

    # Posthog
    # Looks like "{'id': 'posthog_key', 'host': 'https://product.conversations.127.0.0.1.nip.io'}"
    POSTHOG_KEY = values.DictValue(None, environ_name="POSTHOG_KEY", environ_prefix=None)
    POSTHOG_MW_CAPTURE_EXCEPTIONS = values.BooleanValue(
        default=False, environ_name="POSTHOG_MW_CAPTURE_EXCEPTIONS", environ_prefix=None
    )

    STATUS_PAGE_URL = values.Value(None, environ_name="STATUS_PAGE_URL", environ_prefix=None)

    # Easy thumbnails
    THUMBNAIL_EXTENSION = "webp"
    THUMBNAIL_TRANSPARENCY_EXTENSION = "webp"
    THUMBNAIL_DEFAULT_STORAGE_ALIAS = "default"
    THUMBNAIL_ALIASES = {}

    # Session
    SESSION_ENGINE = values.Value(
        "django.contrib.sessions.backends.cache",
        environ_name="SESSION_ENGINE",
        environ_prefix=None,
    )
    SESSION_CACHE_ALIAS = "default"
    SESSION_COOKIE_AGE = values.PositiveIntegerValue(
        default=60 * 60 * 12, environ_name="SESSION_COOKIE_AGE", environ_prefix=None
    )

    # OIDC - Authorization Code Flow
    OIDC_CREATE_USER = values.BooleanValue(
        default=True,
        environ_name="OIDC_CREATE_USER",
    )
    OIDC_RP_SIGN_ALGO = values.Value("RS256", environ_name="OIDC_RP_SIGN_ALGO", environ_prefix=None)
    OIDC_RP_CLIENT_ID = values.Value(
        "conversations", environ_name="OIDC_RP_CLIENT_ID", environ_prefix=None
    )
    OIDC_RP_CLIENT_SECRET = values.Value(
        None,
        environ_name="OIDC_RP_CLIENT_SECRET",
        environ_prefix=None,
    )
    OIDC_OP_URL = values.Value(None, environ_name="OIDC_OP_URL", environ_prefix=None)
    OIDC_OP_JWKS_ENDPOINT = values.Value(environ_name="OIDC_OP_JWKS_ENDPOINT", environ_prefix=None)
    OIDC_OP_AUTHORIZATION_ENDPOINT = values.Value(
        environ_name="OIDC_OP_AUTHORIZATION_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_TOKEN_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_TOKEN_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_USER_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_USER_ENDPOINT", environ_prefix=None
    )
    OIDC_OP_LOGOUT_ENDPOINT = values.Value(
        None, environ_name="OIDC_OP_LOGOUT_ENDPOINT", environ_prefix=None
    )
    OIDC_AUTHENTICATE_CLASS = "lasuite.oidc_login.views.OIDCAuthenticationRequestView"
    OIDC_CALLBACK_CLASS = "core.authentication.views.OIDCAuthenticationCallbackView"
    OIDC_AUTH_REQUEST_EXTRA_PARAMS = values.DictValue(
        {}, environ_name="OIDC_AUTH_REQUEST_EXTRA_PARAMS", environ_prefix=None
    )
    OIDC_RP_SCOPES = values.Value(
        "openid email", environ_name="OIDC_RP_SCOPES", environ_prefix=None
    )
    # Restrict login and account creation to users exposing one of these roles
    # in their OIDC "roles" claim. Empty (default) disables the restriction.
    OIDC_ALLOWED_ROLES = values.ListValue(
        [], environ_name="OIDC_ALLOWED_ROLES", environ_prefix=None
    )
    LOGIN_REDIRECT_URL = values.Value(None, environ_name="LOGIN_REDIRECT_URL", environ_prefix=None)
    LOGIN_REDIRECT_URL_FAILURE = values.Value(
        None, environ_name="LOGIN_REDIRECT_URL_FAILURE", environ_prefix=None
    )
    LOGOUT_REDIRECT_URL = values.Value(
        None, environ_name="LOGOUT_REDIRECT_URL", environ_prefix=None
    )
    OIDC_USE_NONCE = values.BooleanValue(
        default=True, environ_name="OIDC_USE_NONCE", environ_prefix=None
    )
    OIDC_REDIRECT_REQUIRE_HTTPS = values.BooleanValue(
        default=False, environ_name="OIDC_REDIRECT_REQUIRE_HTTPS", environ_prefix=None
    )
    OIDC_REDIRECT_ALLOWED_HOSTS = values.ListValue(
        default=[], environ_name="OIDC_REDIRECT_ALLOWED_HOSTS", environ_prefix=None
    )
    OIDC_STORE_ID_TOKEN = values.BooleanValue(
        default=True, environ_name="OIDC_STORE_ID_TOKEN", environ_prefix=None
    )
    OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION = values.BooleanValue(
        default=True,
        environ_name="OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION",
        environ_prefix=None,
    )
    OIDC_USE_PKCE = values.BooleanValue(
        default=False, environ_name="OIDC_USE_PKCE", environ_prefix=None
    )
    OIDC_PKCE_CODE_CHALLENGE_METHOD = values.Value(
        default="S256",
        environ_name="OIDC_PKCE_CODE_CHALLENGE_METHOD",
        environ_prefix=None,
    )
    OIDC_PKCE_CODE_VERIFIER_SIZE = values.IntegerValue(
        default=64, environ_name="OIDC_PKCE_CODE_VERIFIER_SIZE", environ_prefix=None
    )
    OIDC_STORE_ACCESS_TOKEN = values.BooleanValue(
        default=False, environ_name="OIDC_STORE_ACCESS_TOKEN", environ_prefix=None
    )
    OIDC_STORE_REFRESH_TOKEN = values.BooleanValue(
        default=False, environ_name="OIDC_STORE_REFRESH_TOKEN", environ_prefix=None
    )
    OIDC_STORE_REFRESH_TOKEN_KEY = values.Value(
        default=None,
        environ_name="OIDC_STORE_REFRESH_TOKEN_KEY",
        environ_prefix=None,
    )

    # WARNING: Enabling this setting allows multiple user accounts to share the same email
    # address. This may cause security issues and is not recommended for production use when
    # email is activated as fallback for identification (see previous setting).
    OIDC_ALLOW_DUPLICATE_EMAILS = values.BooleanValue(
        default=False,
        environ_name="OIDC_ALLOW_DUPLICATE_EMAILS",
        environ_prefix=None,
    )

    USER_OIDC_ESSENTIAL_CLAIMS = values.ListValue(
        default=[], environ_name="USER_OIDC_ESSENTIAL_CLAIMS", environ_prefix=None
    )

    OIDC_USERINFO_FULLNAME_FIELDS = values.ListValue(
        default=["first_name", "last_name"],
        environ_name="OIDC_USERINFO_FULLNAME_FIELDS",
        environ_prefix=None,
    )
    OIDC_USERINFO_SHORTNAME_FIELD = values.Value(
        default="first_name",
        environ_name="OIDC_USERINFO_SHORTNAME_FIELD",
        environ_prefix=None,
    )

    ALLOW_LOGOUT_GET_METHOD = values.BooleanValue(
        default=True, environ_name="ALLOW_LOGOUT_GET_METHOD", environ_prefix=None
    )

    # Activation feature
    ACTIVATION_REQUIRED = values.BooleanValue(
        default=False, environ_name="ACTIVATION_REQUIRED", environ_prefix=None
    )

    BREVO_API_KEY = values.Value(
        default=None,
        environ_name="BREVO_API_KEY",
        environ_prefix=None,
    )
    BREVO_FOLLOWUP_LIST_ID = values.Value(
        default=None,
        environ_name="BREVO_FOLLOWUP_LIST_ID",
        environ_prefix=None,
    )
    BREVO_WAITING_LIST_ID = values.Value(
        default=None,
        environ_name="BREVO_WAITING_LIST_ID",
        environ_prefix=None,
    )

    # AI service
    _llm_configuration_file_path = values.Value(
        os.path.join(BASE_DIR, "conversations/configuration/llm/default.json"),
        environ_name="LLM_CONFIGURATION_FILE_PATH",
        environ_prefix=None,
    )
    LLM_DEFAULT_MODEL_HRID = values.Value(
        "default-model", environ_name="LLM_DEFAULT_MODEL_HRID", environ_prefix=None
    )
    LLM_SUMMARIZATION_MODEL_HRID = values.Value(
        "default-summarization-model",
        environ_name="LLM_SUMMARIZATION_MODEL_HRID",
        environ_prefix=None,
    )
    LLM_FALLBACK_MODEL_HRID_1 = values.Value(
        "", environ_name="LLM_FALLBACK_MODEL_HRID_1", environ_prefix=None
    )
    LLM_FALLBACK_MODEL_HRID_2 = values.Value(
        "", environ_name="LLM_FALLBACK_MODEL_HRID_2", environ_prefix=None
    )
    FAKE_STREAMING_DELAY = values.FloatValue(
        default=0.0025,
        environ_name="FAKE_STREAMING_DELAY",
        environ_prefix=None,  # 25ms
    )
    # Inference-load cooldown: when a model is in degraded health, a user who has
    # spent more than a token threshold over a trailing window is asked to wait
    # before their next request. The wait grows with the overage, scaled by a
    # per-model factor (see LLModel.cooldown_factor) that reflects the GPUs
    # allocated to that model. The thresholds/window/floor are tuned at runtime
    # via the ChatCooldownSettings singleton (core.models), not env vars.
    DEFAULT_ALLOW_CONVERSATION_ANALYTICS = values.BooleanValue(
        default=False,
        environ_name="DEFAULT_ALLOW_CONVERSATION_ANALYTICS",
        environ_prefix=None,
    )
    LLM_MAX_OUTPUT_TOKENS_PER_MESSAGE = values.IntegerValue(
        8192,
        environ_name="LLM_MAX_OUTPUT_TOKENS_PER_MESSAGE",
        environ_prefix=None,
    )
    DEFAULT_ALLOW_SMART_WEB_SEARCH = values.BooleanValue(
        default=False,
        environ_name="DEFAULT_ALLOW_SMART_WEB_SEARCH",
        environ_prefix=None,
    )

    # These settings are default values used in the default LLM_CONFIGURATIONS
    # They allow a deployment with only one model without a specific configuration file
    AI_API_KEY = values.Value(None, environ_name="AI_API_KEY", environ_prefix=None)
    AI_BASE_URL = values.Value(None, environ_name="AI_BASE_URL", environ_prefix=None)
    AI_MODEL = values.Value(None, environ_name="AI_MODEL", environ_prefix=None)
    AI_AGENT_INSTRUCTIONS = values.Value(
        (
            "You are a helpful assistant. "
            "Wrap formulas or any math notation between `\\(...\\)` and `\\[...\\]`, "
            "like `\\(x^2 + y^2 = z^2\\)` for inline formula or `\\[C_l\\]` for display. "
            "You must use Markdown to format your answers except when asked otherwise. "
        ),
        environ_name="AI_AGENT_INSTRUCTIONS",
        environ_prefix=None,
    )

    # Tools
    AI_AGENT_TOOLS = values.ListValue(
        default=[],
        environ_name="AI_AGENT_TOOLS",
        environ_prefix=None,
    )

    # Uploaded files
    RAG_FILES_ACCEPTED_FORMATS = values.ListValue(
        default=[
            # docx files
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            # pptx files
            "application/vnd.openxmlformats-officedocument.presentationml.presentation",
            # xlsx and xls files
            "application/vnd.ms-excel",
            "application/excel",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            # txt and csv files
            "text/plain",
            "text/csv",
            "application/csv",
            # pdf files
            "application/pdf",
            # html files
            "text/html",
            "application/xhtml+xml",
            # markdown files
            "text/markdown",
            "application/markdown",
            "application/x-markdown",
            # outlook msg files
            "application/vnd.ms-outlook",
            # images
            "image/jpeg",
            "image/png",
            "image/gif",
            "image/webp",
            "application/vnd.oasis.opendocument.text",
        ],
        environ_name="RAG_FILES_ACCEPTED_FORMATS",
        environ_prefix=None,
    )

    # Project attachment caps - enforced at upload time to bound per-turn token
    # cost. Every project file contributes a system-prompt listing entry on
    # every conversation turn; every project image is pinned to every turn.
    # Both caps are deliberately conservative; raise via env vars for projects
    # that legitimately need more (e.g. a regulation library).
    PROJECT_FILES_MAX_COUNT = values.PositiveIntegerValue(
        default=10,
        environ_name="PROJECT_FILES_MAX_COUNT",
        environ_prefix=None,
    )
    PROJECT_IMAGES_MAX_COUNT = values.PositiveIntegerValue(
        default=3,
        environ_name="PROJECT_IMAGES_MAX_COUNT",
        environ_prefix=None,
    )

    # Documents
    ALBERT_API_PARSE_TIMEOUT = values.PositiveIntegerValue(
        default=120,  # seconds
        environ_name="ALBERT_API_PARSE_TIMEOUT",
        environ_prefix=None,
    )
    RAG_DOCUMENT_SEARCH_BACKEND = values.Value(
        "chat.agent_rag.document_rag_backends.albert_rag_backend.AlbertRagBackend",
        environ_name="RAG_DOCUMENT_SEARCH_BACKEND",
        environ_prefix=None,
    )
    RAG_DOCUMENT_PARSER = values.Value(
        "chat.agent_rag.document_converter.parser.AlbertParser",
        environ_name="RAG_DOCUMENT_PARSER",
        environ_prefix=None,
    )
    RAG_COLLECTION_INACTIVITY_DAYS = values.PositiveIntegerValue(
        default=30,
        environ_name="RAG_COLLECTION_INACTIVITY_DAYS",
        environ_prefix=None,
    )
    # 10 min: reindex iterates over attachments (storage read + HTTP per doc); 120 s is too tight.
    REINDEX_CLAIM_TIMEOUT_SECONDS = values.PositiveIntegerValue(
        default=600,
        environ_name="REINDEX_CLAIM_TIMEOUT_SECONDS",
        environ_prefix=None,
    )
    DEINDEX_MAX_PER_RUN = values.PositiveIntegerValue(
        default=100,
        environ_name="DEINDEX_MAX_PER_RUN",
        environ_prefix=None,
    )
    DEINDEX_PARALLEL_REQUESTS = values.PositiveIntegerValue(
        default=10,
        environ_name="DEINDEX_PARALLEL_REQUESTS",
        environ_prefix=None,
    )
    SPECIFIC_RAG_DOCUMENT_SEARCH_TOOLS = values.DictValue(
        default={},
        environ_name="SPECIFIC_RAG_DOCUMENT_SEARCH_TOOLS",
        environ_prefix=None,
    )

    # Web search
    RAG_WEB_SEARCH_PROMPT_UPDATE = values.Value(
        """
You are a subject-matter expert assistant. 
You are given :
 - web search result(s) or raw webpage text that may contain navigation, menus, comments, 
   category names, and other unrelated page details.
 - document(s) that may contain text, images, and metadata, formatted in markdown.

**Your mission:**
- Use ONLY the main informational content that directly and factually answers the user's explicit 
  question.
- *Completely ignore and do NOT mention* any of the following in your answer:
    - Web page or site structure
    - Navigation elements, headers, menus, search bars, categories
    - Lists of links, footers, or any site design features
    - Any meta-observations about how the content is organized
- NEVER include sections titled “Website Structure”, “Format”, “Layout”, or similar.
- NEVER narrate, summarize, or analyze how the website is arranged or how links are presented.
- If given a block of mixed web text, locate the relevant information AT THE SENTENCE LEVEL; 
  include ONLY those sentences (possibly paraphrased) that respond to the user’s direct question.
- If the relevant answer cannot be found in the content, simply state: “The provided content 
  does not contain information directly answering the question.” Do not speculate or elaborate.

#### Example output:

> - John Doe criticized Jane the prime minister for "the absence of consultation" with other 
    political forces regarding the 2025 the government budget, focusing on economic policy and 
    spending plans.
> - The country unemployment insurance system is noted as more generous than other neighbor's 
    systems.
> - [If more is needed, continue, but only with factual statements explicitly present in the 
    provided content. Stop when unrelated content begins.]

**Do NOT:**
- Discuss the page’s design, link structure, main/secondary categories, branding, or site 
  navigation tools.
- Invent summaries for structure or offer general commentary about the website.

{search_results}

USER QUESTION:

{user_prompt}
        """,
        environ_name="RAG_WEB_SEARCH_PROMPT_UPDATE",
        environ_prefix=None,
    )
    RAG_WEB_SEARCH_MAX_RESULTS = values.PositiveIntegerValue(
        default=5,
        environ_name="RAG_WEB_SEARCH_MAX_RESULTS",
        environ_prefix=None,
    )
    RAG_WEB_SEARCH_CHUNK_NUMBER = values.PositiveIntegerValue(
        default=4,
        environ_name="RAG_WEB_SEARCH_CHUNK_NUMBER",
        environ_prefix=None,
    )

    # OCR settings for AdaptivePdfParser
    OCR_HRID = values.Value(
        default="etalab-plateform-mistral-medium-2508",
        environ_name="OCR_HRID",
        environ_prefix=None,
    )
    # Specific Mistral OCR model - Designates which Mistral vision model to use for OCR
    OCR_MODEL = values.Value(
        default="mistral-ocr-2512",
        environ_name="OCR_MODEL",
        environ_prefix=None,
    )
    OCR_TIMEOUT = values.PositiveIntegerValue(
        default=240,
        environ_name="OCR_TIMEOUT",
        environ_prefix=None,
    )
    OCR_MAX_RETRIES = values.PositiveIntegerValue(
        default=3,
        environ_name="OCR_MAX_RETRIES",
        environ_prefix=None,
    )

    OCR_RETRY_DELAY = values.PositiveIntegerValue(
        default=5,
        environ_name="OCR_RETRY_DELAY",
        environ_prefix=None,
    )

    OCR_BATCH_PAGES = values.PositiveIntegerValue(
        default=10,
        environ_name="OCR_BATCH_PAGES",
        environ_prefix=None,
    )
    MIN_AVG_CHARS_FOR_TEXT_EXTRACTION = values.PositiveIntegerValue(
        default=200,
        environ_name="MIN_AVG_CHARS_FOR_TEXT_EXTRACTION",
        environ_prefix=None,
    )
    MIN_TEXT_COVERAGE_FOR_TEXT_EXTRACTION = values.FloatValue(
        default=0.7,
        environ_name="MIN_TEXT_COVERAGE_FOR_TEXT_EXTRACTION",
        environ_prefix=None,
    )

    # Summarization
    SUMMARIZATION_SYSTEM_PROMPT = values.Value(
        (
            "You are a helpful assistant that summarizes the content "
            "of documents following user request.\n\n"
        ),
        environ_name="SUMMARIZATION_SYSTEM_PROMPT",
        environ_prefix=None,
    )
    SUMMARIZATION_CHUNK_SIZE = values.PositiveIntegerValue(
        default=20_000,  # Approx 20k words per chunk
        environ_name="SUMMARIZATION_CHUNK_SIZE",
        environ_prefix=None,
    )
    SUMMARIZATION_OVERLAP_SIZE = values.FloatValue(
        default=0.05,  # 5% overlap
        environ_name="SUMMARIZATION_OVERLAP_SIZE",
        environ_prefix=None,
    )
    SUMMARIZATION_CONCURRENT_REQUESTS = values.PositiveIntegerValue(
        default=5,
        environ_name="SUMMARIZATION_CONCURRENT_REQUESTS",
        environ_prefix=None,
    )
    # Token estimation uses cl100k_base (GPT-4 tokenizer); non-OpenAI models
    # (Mistral, Llama, Anthropic) may tokenize 5-15% higher for the same text.
    # The security buffer below absorbs that drift.
    DOCUMENT_CONTEXT_BUDGET_RATIO = values.FloatValue(
        default=0.5,
        environ_name="DOCUMENT_CONTEXT_BUDGET_RATIO",
        environ_prefix=None,
    )
    DOCUMENT_CONTEXT_SECURITY_BUFFER_TOKENS = values.PositiveIntegerValue(
        default=1000,
        environ_name="DOCUMENT_CONTEXT_SECURITY_BUFFER_TOKENS",
        environ_prefix=None,
    )
    # Fallback context window for models that don't declare max_token_context.
    # 8192 is the smallest modern standard (GPT-4 base, Llama 3, Gemma); after
    # applying security buffer and budget ratio the conversation budget lands at
    # ~3 600 tokens, safely within even a genuine 4K-context model.
    DEFAULT_MAX_TOKEN_CONTEXT = values.PositiveIntegerValue(
        default=8192,
        environ_name="DEFAULT_MAX_TOKEN_CONTEXT",
        environ_prefix=None,
    )

    # Tavily API
    TAVILY_API_KEY = values.Value(
        None,  # Tavily API key is not set by default
        environ_name="TAVILY_API_KEY",
        environ_prefix=None,
    )
    TAVILY_MAX_RESULTS = values.PositiveIntegerValue(
        default=5,
        environ_name="TAVILY_MAX_RESULTS",
        environ_prefix=None,
    )
    TAVILY_API_TIMEOUT = values.PositiveIntegerValue(
        default=10,  # seconds
        environ_name="TAVILY_API_TIMEOUT",
        environ_prefix=None,
    )

    # Albert API
    ALBERT_API_KEY = values.Value(
        None,  # Albert API key is not set by default
        environ_name="ALBERT_API_KEY",
        environ_prefix=None,
    )
    ALBERT_API_URL = values.Value(
        "https://albert.api.etalab.gouv.fr",  # Default Albert API URL
        environ_name="ALBERT_API_URL",
        environ_prefix=None,
    )

    ALBERT_API_TIMEOUT = values.PositiveIntegerValue(
        default=30,  # seconds
        environ_name="ALBERT_API_TIMEOUT",
        environ_prefix=None,
    )

    ALBERT_HEALTH_URL = values.Value(
        "https://albert.api.etalab.gouv.fr/health/models",
        environ_name="ALBERT_HEALTH_URL",
        environ_prefix=None,
    )

    ALBERT_HEALTH_TIMEOUT = values.PositiveIntegerValue(
        default=10,
        environ_name="ALBERT_HEALTH_TIMEOUT",
        environ_prefix=None,
    )

    # Project-file RAG indexing (`index_project_attachment`) retries the store
    # call on transient Albert failures (network/timeout, 5xx, 429) before
    # marking the attachment FAILED. Total number of attempts, initial + retries
    # (2 = one retry). Set to 1 to disable retrying.
    RAG_STORE_MAX_ATTEMPTS = values.PositiveIntegerValue(
        default=2,
        environ_name="RAG_STORE_MAX_ATTEMPTS",
        environ_prefix=None,
    )

    # Delay, in seconds, the indexing worker sleeps between store attempts. Kept
    # short: the worker blocks for this duration, so it trades a held slot for
    # clearing brief Albert blips.
    RAG_STORE_RETRY_DELAY_SECONDS = values.PositiveIntegerValue(
        default=3,
        environ_name="RAG_STORE_RETRY_DELAY_SECONDS",
        environ_prefix=None,
    )

    # Find
    FIND_API_KEY = values.Value(
        None,
        environ_name="FIND_API_KEY",
        environ_prefix=None,
    )
    FIND_API_URL = values.Value(
        "https://app-find/api",
        environ_name="FIND_API_URL",
        environ_prefix=None,
    )
    FIND_API_TIMEOUT = values.PositiveIntegerValue(
        default=30,  # seconds
        environ_name="FIND_API_TIMEOUT",
        environ_prefix=None,
    )
    # Docs
    DOCS_BASE_URL = values.Value(None, environ_name="DOCS_BASE_URL", environ_prefix=None)
    DOCS_API_TIMEOUT = values.PositiveIntegerValue(
        default=30, environ_name="DOCS_API_TIMEOUT", environ_prefix=None
    )

    # Logging
    # We want to make it easy to log to console but by default we log production
    # to Sentry and don't want to log to console.
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "{asctime} {name} {levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        # Override root logger to send it to console
        "root": {
            "handlers": ["console"],
            "level": values.Value(
                "INFO", environ_name="LOGGING_LEVEL_LOGGERS_ROOT", environ_prefix=None
            ),
        },
        "loggers": {
            "core": {
                "handlers": ["console"],
                "level": values.Value(
                    "INFO",
                    environ_name="LOGGING_LEVEL_LOGGERS_APP",
                    environ_prefix=None,
                ),
                "propagate": False,
            },
            "conversations.security": {
                "handlers": ["console"],
                "level": values.Value(
                    "INFO",
                    environ_name="LOGGING_LEVEL_LOGGERS_SECURITY",
                    environ_prefix=None,
                ),
                "propagate": False,
            },
        },
    }

    # LLM Instrumentation
    LANGFUSE_ENABLED = values.BooleanValue(
        default=False, environ_name="LANGFUSE_ENABLED", environ_prefix=None
    )
    LANGFUSE_PUBLIC_KEY = values.Value(
        None, environ_name="LANGFUSE_PUBLIC_KEY", environ_prefix=None
    )
    LANGFUSE_SECRET_KEY = values.Value(
        None, environ_name="LANGFUSE_SECRET_KEY", environ_prefix=None
    )
    LANGFUSE_HOST = values.Value(None, environ_name="LANGFUSE_HOST", environ_prefix=None)
    LANGFUSE_DEBUG = values.BooleanValue(
        default=False, environ_name="LANGFUSE_DEBUG", environ_prefix=None
    )
    LANGFUSE_MEDIA_UPLOAD_ENABLED = values.BooleanValue(
        default=False, environ_name="LANGFUSE_MEDIA_UPLOAD_ENABLED", environ_prefix=None
    )
    AUTO_TITLE_AFTER_USER_MESSAGES = values.PositiveIntegerValue(
        default=None, environ_name="AUTO_TITLE_AFTER_USER_MESSAGES", environ_prefix=None
    )
    # WARNING: Testing purpose only. Do not use in production.
    WARNING_MOCK_CONVERSATION_AGENT = values.BooleanValue(
        default=False,
        environ_name="WARNING_MOCK_CONVERSATION_AGENT",
        environ_prefix=None,
    )

    # Default keepalive interval: 55s (safely below typical 60s proxy timeouts)
    # Prevents connection drops during long stream pauses while providing 5s safety margin.
    KEEPALIVE_INTERVAL = values.PositiveIntegerValue(
        default=55, environ_name="KEEPALIVE_INTERVAL", environ_prefix=None
    )

    # Celery
    # Broker uses Redis db 0 to avoid colliding with the cache (db 1 in production,
    # db 2 in development).
    CELERY_BROKER_URL = values.Value(
        "redis://redis:6379/0", environ_name="CELERY_BROKER_URL", environ_prefix=None
    )
    # Broker-specific tuning passed through to the Redis transport (e.g. visibility_timeout).
    # Empty means defaults; raise visibility_timeout if any task can run longer than 1h.
    CELERY_BROKER_TRANSPORT_OPTIONS = values.DictValue(
        {},
        environ_name="CELERY_BROKER_TRANSPORT_OPTIONS",
        environ_prefix=None,
    )
    # Maps task names to queues (e.g. {"chat.tasks.*": {"queue": "heavy"}}) so heavy and
    # fast tasks can run on separate workers. Empty means everything uses the default queue.
    CELERY_TASK_ROUTES = values.DictValue(
        {},
        environ_name="CELERY_TASK_ROUTES",
        environ_prefix=None,
    )
    # Per-task wall-clock budget. The soft limit raises SoftTimeLimitExceeded, which the
    # parse path catches and records as a visible FAILED state; the hard limit SIGKILLs the
    # worker child (prefork pool) so a runaway or malicious parse (zip bomb, entity blowup)
    # can't pin a worker indefinitely or grow memory unbounded. Eager mode ignores both.
    CELERY_TASK_SOFT_TIME_LIMIT = values.IntegerValue(
        180,
        environ_name="CELERY_TASK_SOFT_TIME_LIMIT",
        environ_prefix=None,
    )
    CELERY_TASK_TIME_LIMIT = values.IntegerValue(
        300,
        environ_name="CELERY_TASK_TIME_LIMIT",
        environ_prefix=None,
    )

    # pylint: disable=invalid-name
    @property
    def ENVIRONMENT(self):
        """Environment in which the application is launched."""
        return self.__class__.__name__.lower()

    # pylint: disable=invalid-name
    @property
    def RELEASE(self):
        """
        Return the release information.

        Delegate to the module function to enable easier testing.
        """
        return get_release()

    @property
    def FEATURE_FLAGS(self) -> FeatureFlags:  # pylint: disable=invalid-name
        """
        Return a dictionary of feature flags for the application.
        This can be used to enable or disable features dynamically.
        """
        features = FeatureFlags(
            **{
                field_name: FeatureToggle[
                    values.Value(
                        field.default.name,
                        environ_name=f"FEATURE_FLAG_{field_name.upper()}",
                        environ_prefix=None,
                    )
                ]
                for field_name, field in FeatureFlags.model_fields.items()
            }
        )

        # Sanity check to ensure that if document upload is enabled, a backend is set
        if features.document_upload and not self.RAG_DOCUMENT_SEARCH_BACKEND:
            raise RuntimeError(
                "RAG_DOCUMENT_SEARCH_BACKEND is not set, "
                "but document_upload feature flag is enabled."
            )

        return features

    @property
    def LLM_CONFIGURATIONS(self):
        """
        Return the LLM configuration loaded from the configuration file.

        The configuration is lazy loaded to allow settings access and settings update in tests.
        """
        return lazy(load_llm_configuration, dict)(self._llm_configuration_file_path)

    @pristinemethod
    def POSTHOG_MW_REQUEST_FILTER(self, request):  # pylint: disable=bad-staticmethod-argument, invalid-name, unused-argument
        """Return a function that filters requests to be sent to Posthog."""
        return not request.path.startswith(
            (
                "/__heartbeat__",
                "/__lbheartbeat__",
                "/admin",
            )
        )

    @pristinemethod
    def POSTHOG_MW_EXTRA_TAGS(self, request):  # pylint: disable=bad-staticmethod-argument, invalid-name, unused-argument
        """Return extra tags to be sent to Posthog."""
        return {
            "$host": request.get_host(),
            "$environment": self.ENVIRONMENT,
            "$release": self.RELEASE,
        }

    @classmethod
    def _validate_docs_configuration(cls):
        """Validate the "Edit in Docs" settings.

        DocsClient forwards the user's OIDC bearer token and document content to
        DOCS_BASE_URL, so it requires stored access tokens and an encrypted endpoint.
        """
        if not cls.DOCS_BASE_URL:
            return

        if not cls.OIDC_STORE_ACCESS_TOKEN:
            raise ValueError(
                "DOCS_BASE_URL is set but OIDC_STORE_ACCESS_TOKEN is not enabled. "
                "The Docs integration requires OIDC access tokens to be stored in the session."
            )

        # Reject plaintext endpoints — except localhost for local development.
        docs_url = urlparse(cls.DOCS_BASE_URL)
        is_local = docs_url.hostname in ("localhost", "127.0.0.1", "::1")
        if docs_url.scheme != "https" and not is_local:
            raise ValueError(
                "DOCS_BASE_URL must use HTTPS to avoid leaking the forwarded OIDC "
                "access token and document content over an unencrypted connection "
                "(localhost is exempted for local development)."
            )

    @classmethod
    def post_setup(cls):
        """Post setup configuration.
        This is the place where you can configure settings that require other
        settings to be loaded.
        """
        super().post_setup()

        # The SENTRY_DSN setting should be available to activate sentry for an environment
        if cls.SENTRY_DSN is not None:
            sentry_sdk.init(
                dsn=cls.SENTRY_DSN,
                environment=cls.__name__.lower(),
                release=get_release(),
                integrations=[DjangoIntegration()],
            )
            sentry_sdk.set_tag("application", "backend")

            # Ignore the logs added by the DockerflowMiddleware
            ignore_logger("request.summary")

        # Enable Posthog if the key is set
        if cls.POSTHOG_KEY:
            posthog.api_key = cls.POSTHOG_KEY["id"]
            posthog.host = cls.POSTHOG_KEY["host"]

        if cls.OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION and cls.OIDC_ALLOW_DUPLICATE_EMAILS:
            raise ValueError(
                "Both OIDC_FALLBACK_TO_EMAIL_FOR_IDENTIFICATION and "
                "OIDC_ALLOW_DUPLICATE_EMAILS cannot be set to True simultaneously. "
            )

        if cls.OIDC_STORE_REFRESH_TOKEN:
            try:
                Fernet(cls.OIDC_STORE_REFRESH_TOKEN_KEY)
            except (TypeError, ValueError) as error:
                raise ValueError(
                    "OIDC_STORE_REFRESH_TOKEN is enabled but OIDC_STORE_REFRESH_TOKEN_KEY "
                    "is not a valid Fernet key (32 url-safe base64-encoded bytes)."
                ) from error

        # File access configuration validation
        if cls.FILE_TO_LLM_MODE == FileToLLMMode.BACKEND_TEMPORARY_URL and not cls.FILE_BACKEND_URL:
            raise ValueError(
                "FILE_TO_LLM_MODE is set to 'backend_temporary_url' but FILE_BACKEND_URL is empty. "
                "Please set FILE_BACKEND_URL to a valid URL for backend temporary file access."
            )

        # Find configuration
        if (
            cls.RAG_DOCUMENT_SEARCH_BACKEND
            == "chat.agent_rag.document_rag_backends.find_rag_backend.FindRagBackend"
            and not all(
                (
                    cls.FIND_API_KEY,
                    cls.FIND_API_URL,
                    cls.OIDC_STORE_ACCESS_TOKEN,
                    cls.OIDC_STORE_REFRESH_TOKEN,
                )
            )
        ):
            raise ValueError(
                f"{cls.RAG_DOCUMENT_SEARCH_BACKEND} requires FIND_API_KEY, FIND_API_URL, "
                "OIDC_STORE_ACCESS_TOKEN and OIDC_STORE_REFRESH_TOKEN to be set."
            )

        # Docs configuration
        cls._validate_docs_configuration()

        # Document context budget ratio must be a fraction (0 disables full inlining,
        # 1 dedicates the entire model context to documents).
        if not 0 <= cls.DOCUMENT_CONTEXT_BUDGET_RATIO <= 1:
            raise ValueError(
                "DOCUMENT_CONTEXT_BUDGET_RATIO must be between 0 and 1, "
                f"got {cls.DOCUMENT_CONTEXT_BUDGET_RATIO}."
            )

        # OCR configuration validation
        # Note: we call load_llm_configuration directly because LLM_CONFIGURATIONS is a
        # @property returning a lazy object, which cannot be accessed via cls in a classmethod.
        if cls.RAG_DOCUMENT_PARSER == "chat.agent_rag.document_converter.parser.AdaptivePdfParser":
            llm_configs = load_llm_configuration(cls._llm_configuration_file_path)
            if cls.OCR_HRID not in llm_configs:
                raise ValueError(
                    f"OCR_HRID '{cls.OCR_HRID}' not found in LLM_CONFIGURATIONS. "
                    "Please add a matching provider entry or set OCR_HRID to an existing key."
                )

        # Langfuse initialization
        if cls.LANGFUSE_ENABLED:
            if not cls.LANGFUSE_MEDIA_UPLOAD_ENABLED:
                os.environ["LANGFUSE_MEDIA_UPLOAD_ENABLED"] = "false"
            Langfuse(
                public_key=cls.LANGFUSE_PUBLIC_KEY,
                secret_key=cls.LANGFUSE_SECRET_KEY,
                host=cls.LANGFUSE_HOST,
                environment=cls.__name__.lower(),
                release=get_release(),
                debug=cls.LANGFUSE_DEBUG,
            )


class Build(Base):
    """Settings used when the application is built.

    This environment should not be used to run the application. Just to build it with non-blocking
    settings.
    """

    SECRET_KEY = values.Value("DummyKey")
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": values.Value(
                "whitenoise.storage.CompressedManifestStaticFilesStorage",
                environ_name="STORAGES_STATICFILES_BACKEND",
            ),
        },
    }


class Development(Base):
    """
    Development environment settings

    We set DEBUG to True and configure the server to respond from all hosts.
    """

    ALLOWED_HOSTS = ["*"]
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = ["http://localhost:8072", "http://localhost:3000"]
    DEBUG = True

    SESSION_COOKIE_NAME = "conversations_sessionid"

    USE_SWAGGER = True
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379/2",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "TIMEOUT": values.IntegerValue(
                30,  # timeout in seconds
                environ_name="CACHES_DEFAULT_TIMEOUT",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        },
    }

    def __init__(self):
        # pylint: disable=invalid-name
        self.INSTALLED_APPS += ["django_extensions", "drf_spectacular_sidecar"]


class Test(Base):
    """Test environment settings"""

    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]
    USE_SWAGGER = True
    # Static files are not used in the test environment
    # Tests are raising warnings because the /data/static directory does not exist
    STATIC_ROOT = None

    # Run celery tasks synchronously in tests, without a broker.
    CELERY_TASK_ALWAYS_EAGER = True

    os.environ["OPENAI_AGENTS_DISABLE_TRACING"] = "true"

    # -------------------------------------------------------------------------
    # Deterministic test settings.
    #
    # Tests get a dedicated, controlled environment: the ``app-test`` compose
    # service (docker ``make test``) and pytest-dotenv (host / CI) load
    # ``env.d/test`` instead of the developer-local ``env.d/development/common``.
    # With that file gone, every setting Base derives from an environment
    # variable falls back to Base's coded default, which is already
    # deterministic. ``env.d/test`` only overrides the handful of settings whose
    # Base default is unusable in tests (secrets, service credentials, provider
    # endpoints/models); see that file.
    #
    # What stays pinned here is what is genuinely test-specific and NOT env
    # -backed in Base:
    #   - infra topology (Postgres, MinIO) describes the network, not behavior:
    #     it defaults to the docker-compose hostnames but stays env-overridable
    #     so pytest also runs on the host / in CI (repo-root .env or the CI job
    #     env point at the published ports);
    #   - test-only backends and structures (dummy malware backend, DRF/OpenAPI,
    #     CORS headers, storages);
    #   - the large AI/RAG prompts kept as short placeholders (the real ones are
    #     only exercised by tests that override them explicitly).
    #
    # chat/tests/test_settings_isolation.py asserts the resulting settings are
    # deterministic.
    # -------------------------------------------------------------------------

    # -- Infra: docker-compose topology by default, env-overridable ------------
    # Tests run from two vantage points: inside docker (DB_HOST=postgresql via
    # the app-test service defaults) and on the host / CI (DB_HOST=localhost via
    # the repo-root .env or the CI job env).
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": "conversations",
            "USER": "dinum",
            "PASSWORD": "pass",
            "HOST": os.environ.get("DB_HOST", "postgresql"),
            "PORT": int(os.environ.get("DB_PORT", "5432")),
        }
    }

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

    # AWS_S3_ENDPOINT_URL: docker default is the compose MinIO host; the repo
    # -root .env / CI job env point it at the published port.
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "http://minio:9000")

    # -- Attachments: dummy malware backend ------------------------------------
    MALWARE_DETECTION = {
        "BACKEND": "lasuite.malware_detection.backends.dummy.DummyBackend",
        "PARAMETERS": {
            "callback_path": ("core.file_upload.malware_detection.malware_detection_callback"),
        },
    }

    # -- DRF / OpenAPI ---------------------------------------------------------
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            "mozilla_django_oidc.contrib.drf.OIDCAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ),
        "DEFAULT_PARSER_CLASSES": [
            "rest_framework.parsers.JSONParser",
            "nested_multipart_parser.drf.DrfNestedParser",
        ],
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
        ],
        "EXCEPTION_HANDLER": "core.api.exception_handler",
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 20,
        "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
        "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
        "DEFAULT_THROTTLE_RATES": {
            "attachment_upload": "60/minute",
            "attachment_auth": "60/minute",
            "file-stream": "60/minute",
        },
    }

    SPECTACULAR_SETTINGS = {
        "TITLE": "Conversations API",
        "DESCRIPTION": "This is the conversations API schema.",
        "VERSION": "1.0.0",
        "SERVE_INCLUDE_SCHEMA": False,
        "ENABLE_DJANGO_DEPLOY_CHECK": False,
        "COMPONENT_SPLIT_REQUEST": True,
        "SWAGGER_UI_DIST": "SIDECAR",
        "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
        "REDOC_DIST": "SIDECAR",
    }

    # -- CORS ------------------------------------------------------------------
    CORS_ALLOW_HEADERS = [
        "x-posthog-distinct-id",
        "x-posthog-session-id",
    ] + list(default_headers)

    # -- AI / RAG prompt placeholders ------------------------------------------
    # Kept as short placeholders instead of Base's large production prompts;
    # tests that assert on prompt content override these explicitly.
    AI_AGENT_INSTRUCTIONS = "You are a helpful assistant."

    RAG_WEB_SEARCH_PROMPT_UPDATE = (
        "Answer using the search results:\n{search_results}\nQuestion: {user_prompt}"
    )

    # -- Logging ---------------------------------------------------------------
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {
                "format": "{asctime} {name} {levelname} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "simple",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": "INFO",
        },
        "loggers": {
            "core": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
            "conversations.security": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }

    def __init__(self):
        # pylint: disable=invalid-name
        self.INSTALLED_APPS += ["drf_spectacular_sidecar"]

    @property
    def FEATURE_FLAGS(self) -> FeatureFlags:  # pylint: disable=invalid-name
        """
        In the test environment, we want to enable all features to test them.

        We willingly call the super to validate it works (coverage), but we override all
        the feature flags to always enabled.
        """
        _feature_flags = super().FEATURE_FLAGS

        for field_name in FeatureFlags.model_fields.keys():
            setattr(_feature_flags, field_name, FeatureToggle.ENABLED)

        return _feature_flags

    @classmethod
    def post_setup(cls):
        """Post setup configuration."""
        super().post_setup()

        # Force logger propagation to allow caplog to work
        # see https://github.com/pytest-dev/pytest/issues/3697
        cls.LOGGING["loggers"]["core"]["propagate"] = True


class ContinuousIntegration(Test):
    """
    Continuous Integration environment settings

    nota bene: it should inherit from the Test environment.
    """


class Production(Base):
    """
    Production environment settings

    You must define the ALLOWED_HOSTS environment variable in Production
    configuration (and derived configurations):
    ALLOWED_HOSTS=["foo.com", "foo.fr"]
    """

    # Security
    # Add allowed host from environment variables.
    # The machine hostname is added by default,
    # it makes the application pingable by a load balancer on the same machine by example
    ALLOWED_HOSTS = [
        *values.ListValue([], environ_name="ALLOWED_HOSTS"),
        gethostbyname(gethostname()),
    ]
    CSRF_TRUSTED_ORIGINS = values.ListValue([])
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # SECURE_PROXY_SSL_HEADER allows to fix the scheme in Django's HttpRequest
    # object when your application is behind a reverse proxy.
    #
    # Keep this SECURE_PROXY_SSL_HEADER configuration only if :
    # - your Django app is behind a proxy.
    # - your proxy strips the X-Forwarded-Proto header from all incoming requests
    # - Your proxy sets the X-Forwarded-Proto header and sends it to Django
    #
    # In other cases, you should comment the following line to avoid security issues.
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 60
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SECURE_REDIRECT_EXEMPT = [
        "^__lbheartbeat__",
        "^__heartbeat__",
    ]

    # Modern browsers require to have the `secure` attribute on cookies with `Samesite=none`
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

    # Privacy
    SECURE_REFERRER_POLICY = "same-origin"

    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": values.Value(
                "redis://redis:6379/1",
                environ_name="REDIS_URL",
                environ_prefix=None,
            ),
            "TIMEOUT": values.IntegerValue(
                30,  # timeout in seconds
                environ_name="CACHES_DEFAULT_TIMEOUT",
                environ_prefix=None,
            ),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": values.Value(
                "conversations",
                environ_name="CACHES_KEY_PREFIX",
                environ_prefix=None,
            ),
        },
    }

    @property
    def LLM_CONFIGURATIONS(self):
        """
        Return the LLM configuration loaded from the configuration file.

        The configuration is lazy loaded to allow settings access and cached to reduce footprint.
        """
        return lazy(cached_load_llm_configuration, dict)(self._llm_configuration_file_path)


class Feature(Production):
    """
    Feature environment settings

    nota bene: it should inherit from the Production environment.
    """


class Staging(Production):
    """
    Staging environment settings

    nota bene: it should inherit from the Production environment.
    """


class PreProduction(Production):
    """
    Pre-production environment settings

    nota bene: it should inherit from the Production environment.
    """


class Demo(Production):
    """
    Demonstration environment settings

    nota bene: it should inherit from the Production environment.
    """

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
