name: Helmfile lint
run-name: Helmfile lint

on:
  push:
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  helmfile-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/helmfile/helmfile:v0.171.0@sha256:1b1d83b5db69c3bb9e8f6855a8076bdc18c816332af1208c43b4e294a74dd33f
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      with:
        persist-credentials: false
    -
      name: Helmfile lint
      shell: bash
      run: |
        set -e
        HELMFILE=src/helm/helmfile.yaml.gotmpl
        environments=$(awk 'BEGIN {in_env=0} /^environments:/ {in_env=1; next} /^---/ {in_env=0} in_env && /^  [^ ]/ {gsub(/^  /,""); gsub(/:.*$/,""); print}' "$HELMFILE")
        for env in $environments; do
          echo "################### $env lint ###################"
          helmfile -e $env -f $HELMFILE lint || exit 1
          echo -e "\n"
        done
